# baseURL = "http://example.org/"
# languageCode = "en-us"
# title = "My New Hugo Site"

# baseurl = "/"
baseurl = "https://yoshwata-blog.netlify.com/"
languageCode = "en-us"
theme = "hello-friend-ng"
googleAnalytics = "UA-139550190-1"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Djordje Atlialp"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Hello yoshwata NG"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "yoshwata $ cd ~/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"

# And you can even create generic menu
# [menu]
#   [[menu.main]]
#     identifier = "about"
#     name       = "About"
#     url        = "/about"
#   [[menu.main]]
#     identifier = "posts"
#     name       = "Posts"
#     url        = "/posts"

